name: Matrix Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        node-version: [16, 17, 18]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: node-key-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run build